services:
  db:
    image: postgres:15
    container_name: carpool-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: carpool
    volumes:
      - ./postgres_data:/var/lib/postgresql/data # DB가 꺼져도 데이터가 보존됩니다.

  redis:
    image: redis:7-alpine
    container_name: carpool-redis
    ports:
      - "6379:6379"

  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: carpool-app
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/carpool
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379